rjob submit --name=slime-rl-math-16-gpu --gpu=8 --memory=1500000 --cpu=128 \
--charged-group=stu --private-machine=group \
--mount=gpfs://gpfs1/ailab-sys:/mnt/shared-storage-user/ailab-sys \
--image=registry.h.pjlab.org.cn/ailab-sys-sys_gpu/gaia:slimerl \
-P 2 \
--priority=9 \
--host-network=true \
--negative-tags node/gpu-lg-cmc-h-h200-1113.host.h.pjlab.org.cn \
--custom-resources rdma/mlnx_shared=8 \
--custom-resources mellanox.com/mlnx_rdma=1 \
-e DISTRIBUTED_JOB=true \
-- bash -exc /mnt/shared-storage-user/ailab-sys/zhoujiecheng/projs/robust_rl/OpenClaw-RL/slime/scripts/fault_tolerance/run-no-fast-restart-weight-update-smoke-16gpu.sh