#!/bin/bash

# Rollout-only launcher with static concurrency and fully synchronous rollout.
#
# Properties:
# - no online scheduler
# - no oversampling beyond the target rollout batch
# - no rolling refill
#
# Usage:
#   bash swe-rl/scripts/run_swe_rl_static_rollout_only_sync.sh 128
#   STATIC_MAX_CONCURRENCY=256 bash swe-rl/scripts/run_swe_rl_static_rollout_only_sync.sh

set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"
SWE_RL_DIR="$(cd -- "${SCRIPT_DIR}/.." &>/dev/null && pwd)"
SLIME_DIR="$(cd -- "${SWE_RL_DIR}/../slime" &>/dev/null && pwd)"

STATIC_MAX_CONCURRENCY="${STATIC_MAX_CONCURRENCY:-128}"
if [[ $# -gt 0 && "$1" =~ ^[0-9]+$ ]]; then
    STATIC_MAX_CONCURRENCY="$1"
    shift
fi

if ! [[ "${STATIC_MAX_CONCURRENCY}" =~ ^[0-9]+$ ]] || [[ "${STATIC_MAX_CONCURRENCY}" -le 0 ]]; then
    echo "ERROR: STATIC_MAX_CONCURRENCY must be a positive integer, got '${STATIC_MAX_CONCURRENCY}'"
    exit 1
fi

# Keep control-plane throughput aligned with static rollout concurrency by default.
CONTROL_PLANE_CONCURRENCY="${CONTROL_PLANE_CONCURRENCY:-${STATIC_MAX_CONCURRENCY}}"
if [[ "${CONTROL_PLANE_CONCURRENCY}" -gt "${STATIC_MAX_CONCURRENCY}" ]]; then
    CONTROL_PLANE_CONCURRENCY="${STATIC_MAX_CONCURRENCY}"
fi

# Fully synchronous rollout settings:
# - every prompt contributes exactly one sample by default
# - over_sampling_batch_size equals rollout_batch_size
# - rolling refill is disabled
export DEBUG_MODE=${DEBUG_MODE:-1}
export NUM_ROLLOUT=${NUM_ROLLOUT:-1}
export ROLLOUT_BATCH_SIZE=${ROLLOUT_BATCH_SIZE:-128}
export N_SAMPLES_PER_PROMPT=${N_SAMPLES_PER_PROMPT:-1}
export OVER_SAMPLING_BATCH_SIZE=${OVER_SAMPLING_BATCH_SIZE:-${ROLLOUT_BATCH_SIZE}}
export SLIME_ENABLE_ROLLING_OVERSAMPLING_REFILL=${SLIME_ENABLE_ROLLING_OVERSAMPLING_REFILL:-0}
TARGET_TOTAL_SAMPLES=$((ROLLOUT_BATCH_SIZE * N_SAMPLES_PER_PROMPT))

if [[ "${OVER_SAMPLING_BATCH_SIZE}" -ne "${ROLLOUT_BATCH_SIZE}" ]]; then
    echo "ERROR: synchronous rollout requires OVER_SAMPLING_BATCH_SIZE == ROLLOUT_BATCH_SIZE"
    echo "       got OVER_SAMPLING_BATCH_SIZE=${OVER_SAMPLING_BATCH_SIZE}, ROLLOUT_BATCH_SIZE=${ROLLOUT_BATCH_SIZE}"
    exit 1
fi

if [[ "${SLIME_ENABLE_ROLLING_OVERSAMPLING_REFILL}" != "0" ]]; then
    echo "ERROR: synchronous rollout requires SLIME_ENABLE_ROLLING_OVERSAMPLING_REFILL=0"
    exit 1
fi

# Static baseline mode: fixed caps only.
export SWE_ENABLE_ONLINE_ENV_DOCKER_SCHEDULER=${SWE_ENABLE_ONLINE_ENV_DOCKER_SCHEDULER:-0}
export SWE_SCHED_VERBOSE_LOGGING=${SWE_SCHED_VERBOSE_LOGGING:-0}
export SWE_SCHED_USE_REALTIME_SERVER_MEMORY=${SWE_SCHED_USE_REALTIME_SERVER_MEMORY:-0}

export SWE_STATIC_CAPACITY_HEADROOM=${SWE_STATIC_CAPACITY_HEADROOM:-8}
STATIC_CAPACITY_LIMIT=$((STATIC_MAX_CONCURRENCY + SWE_STATIC_CAPACITY_HEADROOM))
CONTROL_PLANE_CAPACITY_LIMIT=$((CONTROL_PLANE_CONCURRENCY + SWE_STATIC_CAPACITY_HEADROOM))

export SWE_POOL_MAX_TOTAL_LEASES=${SWE_POOL_MAX_TOTAL_LEASES:-${STATIC_CAPACITY_LIMIT}}
export SWE_MAX_CONTAINERS_PER_NODE=${SWE_MAX_CONTAINERS_PER_NODE:-${STATIC_CAPACITY_LIMIT}}
export SWE_MAX_CONCURRENT=${SWE_MAX_CONCURRENT:-${STATIC_MAX_CONCURRENCY}}

export SWE_POOL_MAX_CONCURRENT_ALLOCATES=${SWE_POOL_MAX_CONCURRENT_ALLOCATES:-${CONTROL_PLANE_CAPACITY_LIMIT}}
export SWE_POOL_ALLOCATE_MIN_INTERVAL_SEC=${SWE_POOL_ALLOCATE_MIN_INTERVAL_SEC:-0.05}
export SWE_MAX_CONCURRENT_DOCKER_CREATE=${SWE_MAX_CONCURRENT_DOCKER_CREATE:-${CONTROL_PLANE_CAPACITY_LIMIT}}
export SWE_DOCKER_CREATE_MIN_INTERVAL_SEC=${SWE_DOCKER_CREATE_MIN_INTERVAL_SEC:-0.05}
export SWE_POOL_CREATE_TIMEOUT_SEC=${SWE_POOL_CREATE_TIMEOUT_SEC:-1800}
export SWE_ROLLOUT_TIMEOUT=${SWE_ROLLOUT_TIMEOUT:-1800}

export SGLANG_SERVER_CONCURRENCY=${SGLANG_SERVER_CONCURRENCY:-1024}

export TRAIN_ASYNC_ENTRY="${SLIME_DIR}/train_async_rollout_only.py"
export SLIME_EXTRA_ARGS="${SLIME_EXTRA_ARGS:---debug-rollout-only} --sglang-server-concurrency ${SGLANG_SERVER_CONCURRENCY}"

echo "[static-sync] STATIC_MAX_CONCURRENCY=${STATIC_MAX_CONCURRENCY}"
echo "[static-sync] TRAIN_ASYNC_ENTRY=${TRAIN_ASYNC_ENTRY}"
echo "[static-sync] SLIME_EXTRA_ARGS=${SLIME_EXTRA_ARGS}"
echo "[static-sync] SWE_ENABLE_ONLINE_ENV_DOCKER_SCHEDULER=${SWE_ENABLE_ONLINE_ENV_DOCKER_SCHEDULER}"
echo "[static-sync] SWE_STATIC_CAPACITY_HEADROOM=${SWE_STATIC_CAPACITY_HEADROOM}"
echo "[static-sync] STATIC_CAPACITY_LIMIT=${STATIC_CAPACITY_LIMIT}"
echo "[static-sync] CONTROL_PLANE_CAPACITY_LIMIT=${CONTROL_PLANE_CAPACITY_LIMIT}"
echo "[static-sync] SWE_POOL_MAX_TOTAL_LEASES=${SWE_POOL_MAX_TOTAL_LEASES}"
echo "[static-sync] SWE_MAX_CONTAINERS_PER_NODE=${SWE_MAX_CONTAINERS_PER_NODE}"
echo "[static-sync] SWE_MAX_CONCURRENT=${SWE_MAX_CONCURRENT}"
echo "[static-sync] SWE_POOL_MAX_CONCURRENT_ALLOCATES=${SWE_POOL_MAX_CONCURRENT_ALLOCATES}"
echo "[static-sync] SWE_POOL_ALLOCATE_MIN_INTERVAL_SEC=${SWE_POOL_ALLOCATE_MIN_INTERVAL_SEC}"
echo "[static-sync] SWE_POOL_CREATE_TIMEOUT_SEC=${SWE_POOL_CREATE_TIMEOUT_SEC}"
echo "[static-sync] SWE_ROLLOUT_TIMEOUT=${SWE_ROLLOUT_TIMEOUT}"
echo "[static-sync] SWE_MAX_CONCURRENT_DOCKER_CREATE=${SWE_MAX_CONCURRENT_DOCKER_CREATE}"
echo "[static-sync] SWE_DOCKER_CREATE_MIN_INTERVAL_SEC=${SWE_DOCKER_CREATE_MIN_INTERVAL_SEC}"
echo "[static-sync] SGLANG_SERVER_CONCURRENCY=${SGLANG_SERVER_CONCURRENCY}"
echo "[static-sync] NUM_ROLLOUT=${NUM_ROLLOUT}"
echo "[static-sync] ROLLOUT_BATCH_SIZE=${ROLLOUT_BATCH_SIZE}"
echo "[static-sync] N_SAMPLES_PER_PROMPT=${N_SAMPLES_PER_PROMPT}"
echo "[static-sync] OVER_SAMPLING_BATCH_SIZE=${OVER_SAMPLING_BATCH_SIZE}"
echo "[static-sync] TARGET_TOTAL_SAMPLES_PER_ROLLOUT=${TARGET_TOTAL_SAMPLES}"
echo "[static-sync] SLIME_ENABLE_ROLLING_OVERSAMPLING_REFILL=${SLIME_ENABLE_ROLLING_OVERSAMPLING_REFILL}"

SECONDS=0
bash "${SCRIPT_DIR}/run_swe_rl.sh" "$@"
exit_code=$?
elapsed_seconds=${SECONDS}
echo "[static-sync] E2E_WALL_TIME_SECONDS=${elapsed_seconds}"
echo "[static-sync] EXIT_CODE=${exit_code}"
exit "${exit_code}"
