#!/bin/bash

# Wrapper launcher: enable SWE online env docker scheduler, then reuse run_swe_rl.sh.
# Usage:
#   bash swe-rl/scripts/run_swe_rl_online_scheduler.sh

set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"
SWE_RL_DIR="$(cd -- "${SCRIPT_DIR}/.." &>/dev/null && pwd)"
EXPORT_ROOT=${EXPORT_ROOT:-"${SWE_RL_DIR}/../export"}

# Enable online scheduler by default.
export SWE_ENABLE_ONLINE_ENV_DOCKER_SCHEDULER=${SWE_ENABLE_ONLINE_ENV_DOCKER_SCHEDULER:-1}
export OVER_SAMPLING_BATCH_SIZE=${OVER_SAMPLING_BATCH_SIZE:-512}
export SWE_SCHED_INTERNAL_MAX_INFLIGHT=${SWE_SCHED_INTERNAL_MAX_INFLIGHT:-512}

# Scheduler runtime knobs (can be overridden externally).
export SWE_SCHED_SAMPLING_INTERVAL_SEC=${SWE_SCHED_SAMPLING_INTERVAL_SEC:-1.0}
export SWE_SCHED_SAFETY_MARGIN=${SWE_SCHED_SAFETY_MARGIN:-0.95}
export SWE_SCHED_MAX_UNKNOWN_REPO_CONCURRENCY=${SWE_SCHED_MAX_UNKNOWN_REPO_CONCURRENCY:-0}
export SWE_SCHED_COLD_START_MEMORY_MULTIPLIER=${SWE_SCHED_COLD_START_MEMORY_MULTIPLIER:-2.5}
export SWE_SCHED_COLD_START_CPU_MULTIPLIER=${SWE_SCHED_COLD_START_CPU_MULTIPLIER:-1.5}
export SWE_SCHED_MEMORY_OVERSELL_RATIO=${SWE_SCHED_MEMORY_OVERSELL_RATIO:-1.2}
export SWE_SCHED_MEMORY_PEAK_SCALE=${SWE_SCHED_MEMORY_PEAK_SCALE:-0.7}
export SWE_SCHED_CPU_OVERSELL_RATIO=${SWE_SCHED_CPU_OVERSELL_RATIO:-2.5}
export SWE_SCHED_DISK_READ_OVERSELL_RATIO=${SWE_SCHED_DISK_READ_OVERSELL_RATIO:-8.0}
export SWE_SCHED_DISK_WRITE_OVERSELL_RATIO=${SWE_SCHED_DISK_WRITE_OVERSELL_RATIO:-8.0}
export SWE_SCHED_STARTUP_MAX_ACTIVE_PROMPTS=${SWE_SCHED_STARTUP_MAX_ACTIVE_PROMPTS:-192}
export SWE_SCHED_STARTUP_CAP_DURATION_SEC=${SWE_SCHED_STARTUP_CAP_DURATION_SEC:-60}
export SWE_SCHED_DISABLE_LIVE_STATS_POLLING=${SWE_SCHED_DISABLE_LIVE_STATS_POLLING:-1}
export SWE_SCHED_USE_RESOURCE_STATS_DIR=${SWE_SCHED_USE_RESOURCE_STATS_DIR:-1}
export SWE_SCHED_USE_REALTIME_SERVER_MEMORY=${SWE_SCHED_USE_REALTIME_SERVER_MEMORY:-1}
export SWE_SCHED_USE_REALTIME_SERVER_CPU=${SWE_SCHED_USE_REALTIME_SERVER_CPU:-1}
export SWE_SCHED_USE_REALTIME_SERVER_DISK=${SWE_SCHED_USE_REALTIME_SERVER_DISK:-1}
export SWE_SCHED_SERVER_MEMORY_REFRESH_SEC=${SWE_SCHED_SERVER_MEMORY_REFRESH_SEC:-2}
export SWE_SCHED_VERBOSE_LOGGING=${SWE_SCHED_VERBOSE_LOGGING:-1}
export SWE_SCHED_BLOCKED_LOG_INTERVAL_SEC=${SWE_SCHED_BLOCKED_LOG_INTERVAL_SEC:-5}
export SWE_SCHED_VERBOSE_LOG_INTERVAL_SEC=${SWE_SCHED_VERBOSE_LOG_INTERVAL_SEC:-10}
export SWE_SCHED_HEAD_BLOCK_REQUEUE_THRESHOLD=${SWE_SCHED_HEAD_BLOCK_REQUEUE_THRESHOLD:-3}
export SWE_SCHED_HEAD_BLOCK_REQUEUE_OFFSET=${SWE_SCHED_HEAD_BLOCK_REQUEUE_OFFSET:-5}
export SWE_SCHED_DURATION_PRIORITY_WEIGHT=${SWE_SCHED_DURATION_PRIORITY_WEIGHT:-0.4}
export SWE_SCHED_DURATION_PRIORITY_REF_SEC=${SWE_SCHED_DURATION_PRIORITY_REF_SEC:-300}
export SWE_SCHED_REALTIME_LOCAL_ACTIVE_DISCOUNT=${SWE_SCHED_REALTIME_LOCAL_ACTIVE_DISCOUNT:-1.0}
export SWE_SCHED_PRESERVE_PROMPT_ORDER=${SWE_SCHED_PRESERVE_PROMPT_ORDER:-0}
export SWE_RESOURCE_STATS_DIR=${SWE_RESOURCE_STATS_DIR:-"${SWE_RL_DIR}/resource_stats"}

# Conservative defaults for repos without history.
export SWE_SCHED_DEFAULT_MEMORY_BYTES=${SWE_SCHED_DEFAULT_MEMORY_BYTES:-1073741824}
export SWE_SCHED_DEFAULT_CPU_PERCENT=${SWE_SCHED_DEFAULT_CPU_PERCENT:-30}
export SWE_SCHED_DEFAULT_DISK_READ_BYTES=${SWE_SCHED_DEFAULT_DISK_READ_BYTES:-104857600}
export SWE_SCHED_DEFAULT_DISK_WRITE_BYTES=${SWE_SCHED_DEFAULT_DISK_WRITE_BYTES:-104857600}

# Do not cap concurrency by env vars; keep infra-side throttles effectively open.
export SWE_POOL_MAX_TOTAL_LEASES=${SWE_POOL_MAX_TOTAL_LEASES:-0}
export SWE_MAX_CONTAINERS_PER_NODE=${SWE_MAX_CONTAINERS_PER_NODE:-1024}
export SWE_POOL_MAX_CONCURRENT_ALLOCATES=${SWE_POOL_MAX_CONCURRENT_ALLOCATES:-64}
export SWE_POOL_ALLOCATE_MIN_INTERVAL_SEC=${SWE_POOL_ALLOCATE_MIN_INTERVAL_SEC:-0.05}
export SWE_SCHED_DOCKER_CREATE_MAX_CONCURRENT=${SWE_SCHED_DOCKER_CREATE_MAX_CONCURRENT:-64}
export SWE_SCHED_DOCKER_CREATE_MIN_INTERVAL_SEC=${SWE_SCHED_DOCKER_CREATE_MIN_INTERVAL_SEC:-0.05}
export SWE_MAX_CONCURRENT_DOCKER_CREATE=${SWE_MAX_CONCURRENT_DOCKER_CREATE:-${SWE_SCHED_DOCKER_CREATE_MAX_CONCURRENT}}
export SWE_DOCKER_CREATE_MIN_INTERVAL_SEC=${SWE_DOCKER_CREATE_MIN_INTERVAL_SEC:-${SWE_SCHED_DOCKER_CREATE_MIN_INTERVAL_SEC}}

# Persisted repo profile path; reused across restarts.
export SWE_REPO_RESOURCE_STATS_PATH=${SWE_REPO_RESOURCE_STATS_PATH:-"${SWE_RL_DIR}/output/swe_rollouts/repo_resource_stats.json"}
mkdir -p "$(dirname "${SWE_REPO_RESOURCE_STATS_PATH}")"

echo "[run_swe_rl_online_scheduler] SWE_ENABLE_ONLINE_ENV_DOCKER_SCHEDULER=${SWE_ENABLE_ONLINE_ENV_DOCKER_SCHEDULER}"
echo "[run_swe_rl_online_scheduler] SWE_SCHED_SAMPLING_INTERVAL_SEC=${SWE_SCHED_SAMPLING_INTERVAL_SEC}"
echo "[run_swe_rl_online_scheduler] SWE_SCHED_SAFETY_MARGIN=${SWE_SCHED_SAFETY_MARGIN}"
echo "[run_swe_rl_online_scheduler] SWE_SCHED_MEMORY_OVERSELL_RATIO=${SWE_SCHED_MEMORY_OVERSELL_RATIO}"
echo "[run_swe_rl_online_scheduler] SWE_SCHED_MEMORY_PEAK_SCALE=${SWE_SCHED_MEMORY_PEAK_SCALE}"
echo "[run_swe_rl_online_scheduler] SWE_SCHED_CPU_OVERSELL_RATIO=${SWE_SCHED_CPU_OVERSELL_RATIO}"
echo "[run_swe_rl_online_scheduler] SWE_SCHED_DISK_READ_OVERSELL_RATIO=${SWE_SCHED_DISK_READ_OVERSELL_RATIO}"
echo "[run_swe_rl_online_scheduler] SWE_SCHED_DISK_WRITE_OVERSELL_RATIO=${SWE_SCHED_DISK_WRITE_OVERSELL_RATIO}"
echo "[run_swe_rl_online_scheduler] SWE_SCHED_USE_REALTIME_SERVER_MEMORY=${SWE_SCHED_USE_REALTIME_SERVER_MEMORY}"
echo "[run_swe_rl_online_scheduler] SWE_SCHED_USE_REALTIME_SERVER_CPU=${SWE_SCHED_USE_REALTIME_SERVER_CPU}"
echo "[run_swe_rl_online_scheduler] SWE_SCHED_USE_REALTIME_SERVER_DISK=${SWE_SCHED_USE_REALTIME_SERVER_DISK}"
echo "[run_swe_rl_online_scheduler] SWE_SCHED_REALTIME_LOCAL_ACTIVE_DISCOUNT=${SWE_SCHED_REALTIME_LOCAL_ACTIVE_DISCOUNT}"
echo "[run_swe_rl_online_scheduler] SWE_SCHED_PRESERVE_PROMPT_ORDER=${SWE_SCHED_PRESERVE_PROMPT_ORDER}"
echo "[run_swe_rl_online_scheduler] SWE_SCHED_SERVER_MEMORY_REFRESH_SEC=${SWE_SCHED_SERVER_MEMORY_REFRESH_SEC}"
echo "[run_swe_rl_online_scheduler] SWE_SCHED_VERBOSE_LOGGING=${SWE_SCHED_VERBOSE_LOGGING}"
echo "[run_swe_rl_online_scheduler] SWE_SCHED_BLOCKED_LOG_INTERVAL_SEC=${SWE_SCHED_BLOCKED_LOG_INTERVAL_SEC}"
echo "[run_swe_rl_online_scheduler] SWE_SCHED_VERBOSE_LOG_INTERVAL_SEC=${SWE_SCHED_VERBOSE_LOG_INTERVAL_SEC}"
echo "[run_swe_rl_online_scheduler] SWE_SCHED_HEAD_BLOCK_REQUEUE_THRESHOLD=${SWE_SCHED_HEAD_BLOCK_REQUEUE_THRESHOLD}"
echo "[run_swe_rl_online_scheduler] SWE_SCHED_HEAD_BLOCK_REQUEUE_OFFSET=${SWE_SCHED_HEAD_BLOCK_REQUEUE_OFFSET}"
echo "[run_swe_rl_online_scheduler] SWE_SCHED_DURATION_PRIORITY_WEIGHT=${SWE_SCHED_DURATION_PRIORITY_WEIGHT}"
echo "[run_swe_rl_online_scheduler] SWE_SCHED_DURATION_PRIORITY_REF_SEC=${SWE_SCHED_DURATION_PRIORITY_REF_SEC}"
echo "[run_swe_rl_online_scheduler] SWE_SCHED_STARTUP_MAX_ACTIVE_PROMPTS=${SWE_SCHED_STARTUP_MAX_ACTIVE_PROMPTS}"
echo "[run_swe_rl_online_scheduler] SWE_SCHED_STARTUP_CAP_DURATION_SEC=${SWE_SCHED_STARTUP_CAP_DURATION_SEC}"
echo "[run_swe_rl_online_scheduler] SWE_POOL_MAX_TOTAL_LEASES=${SWE_POOL_MAX_TOTAL_LEASES}"
echo "[run_swe_rl_online_scheduler] SWE_POOL_MAX_CONCURRENT_ALLOCATES=${SWE_POOL_MAX_CONCURRENT_ALLOCATES}"
echo "[run_swe_rl_online_scheduler] SWE_POOL_ALLOCATE_MIN_INTERVAL_SEC=${SWE_POOL_ALLOCATE_MIN_INTERVAL_SEC}"
echo "[run_swe_rl_online_scheduler] SWE_MAX_CONCURRENT_DOCKER_CREATE=${SWE_MAX_CONCURRENT_DOCKER_CREATE}"
echo "[run_swe_rl_online_scheduler] SWE_DOCKER_CREATE_MIN_INTERVAL_SEC=${SWE_DOCKER_CREATE_MIN_INTERVAL_SEC}"
echo "[run_swe_rl_online_scheduler] SWE_SCHED_INTERNAL_MAX_INFLIGHT=${SWE_SCHED_INTERNAL_MAX_INFLIGHT}"
echo "[run_swe_rl_online_scheduler] OVER_SAMPLING_BATCH_SIZE=${OVER_SAMPLING_BATCH_SIZE}"
echo "[run_swe_rl_online_scheduler] SWE_REPO_RESOURCE_STATS_PATH=${SWE_REPO_RESOURCE_STATS_PATH}"

exec bash "${SCRIPT_DIR}/run_swe_rl.sh" "$@"
