#!/bin/bash

set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"
SWE_RL_DIR="$(cd -- "${SCRIPT_DIR}/.." &>/dev/null && pwd)"
REPO_ROOT="$(cd -- "${SWE_RL_DIR}/.." &>/dev/null && pwd)"

TS="$(date +%Y%m%d_%H%M%S)"
DEBUG_ROOT_DEFAULT="${REPO_ROOT}/export/swe_rollout_checkpoint_debug_${TS}/oracle-no-fault-no-checkpoint"

export EXPORT_ROOT="${EXPORT_ROOT:-${DEBUG_ROOT_DEFAULT}}"
export LOG_DIR="${LOG_DIR:-${EXPORT_ROOT}/logs}"
export SWE_SAVE_TRAJ_DIR="${SWE_SAVE_TRAJ_DIR:-${EXPORT_ROOT}/rollouts}"

mkdir -p "${EXPORT_ROOT}" "${LOG_DIR}" "${SWE_SAVE_TRAJ_DIR}"

LAUNCH_LOG="${LOG_DIR}/launch.log"
ENV_LOG="${LOG_DIR}/env.log"

exec > >(tee -a "${LAUNCH_LOG}") 2>&1

echo "[checkpoint-debug] EXPORT_ROOT=${EXPORT_ROOT}"
echo "[checkpoint-debug] LOG_DIR=${LOG_DIR}"
echo "[checkpoint-debug] SWE_SAVE_TRAJ_DIR=${SWE_SAVE_TRAJ_DIR}"

# Keep this launcher focused on quick reproducible debugging.
export DEBUG_MODE="${DEBUG_MODE:-1}"
export NUM_ROLLOUT="${NUM_ROLLOUT:-1}"
export ROLLOUT_BATCH_SIZE="${ROLLOUT_BATCH_SIZE:-32}"
export N_SAMPLES_PER_PROMPT="${N_SAMPLES_PER_PROMPT:-4}"
export OVER_SAMPLING_BATCH_SIZE="${OVER_SAMPLING_BATCH_SIZE:-${ROLLOUT_BATCH_SIZE}}"
TARGET_TOTAL_SAMPLES="${TARGET_TOTAL_SAMPLES:-$((ROLLOUT_BATCH_SIZE * N_SAMPLES_PER_PROMPT))}"

# Real-rollout checkpoint policy controls.
export SWE_CHECKPOINT_POLICY="${SWE_CHECKPOINT_POLICY:-adaptive-risk}"
export SWE_ADAPTIVE_TAIL_ROOT="${SWE_ADAPTIVE_TAIL_ROOT:-${REPO_ROOT}/export/swe_rollouts_profile_20260325_083236}"
export SWE_ADAPTIVE_CHECKPOINT_BUDGET_SEC="${SWE_ADAPTIVE_CHECKPOINT_BUDGET_SEC:-3.5}"
export SWE_ADAPTIVE_DECISION_INTERVAL_SEC="${SWE_ADAPTIVE_DECISION_INTERVAL_SEC:-1.0}"
export SWE_ADAPTIVE_FAILURE_PROB="${SWE_ADAPTIVE_FAILURE_PROB:-0.015}"
export SWE_ADAPTIVE_MIN_DELTA_ENV_COST_SEC="${SWE_ADAPTIVE_MIN_DELTA_ENV_COST_SEC:-0.1}"
export SWE_ADAPTIVE_MIN_STEPS_BETWEEN_CHECKPOINTS="${SWE_ADAPTIVE_MIN_STEPS_BETWEEN_CHECKPOINTS:-2}"

# Server-side fault injection during env exec.
export SWE_FAULT_INJECTION_ENABLE="${SWE_FAULT_INJECTION_ENABLE:-0}"
export SWE_FAULT_INJECTION_PROB="${SWE_FAULT_INJECTION_PROB:-0.003}"

# Keep rollout infra knobs visible and overridable.
export STATIC_MAX_CONCURRENCY="${STATIC_MAX_CONCURRENCY:-96}"
export SWE_STATIC_CAPACITY_HEADROOM="${SWE_STATIC_CAPACITY_HEADROOM:-8}"
STATIC_CAPACITY_LIMIT=$((STATIC_MAX_CONCURRENCY + SWE_STATIC_CAPACITY_HEADROOM))
export SWE_MAX_CONCURRENT="${SWE_MAX_CONCURRENT:-${STATIC_MAX_CONCURRENCY}}"
export SWE_POOL_MAX_TOTAL_LEASES="${SWE_POOL_MAX_TOTAL_LEASES:-${STATIC_CAPACITY_LIMIT}}"
export SWE_MAX_CONTAINERS_PER_NODE="${SWE_MAX_CONTAINERS_PER_NODE:-${STATIC_CAPACITY_LIMIT}}"
export SWE_POOL_MAX_CONCURRENT_ALLOCATES="${SWE_POOL_MAX_CONCURRENT_ALLOCATES:-${STATIC_CAPACITY_LIMIT}}"
export SWE_MAX_CONCURRENT_DOCKER_CREATE="${SWE_MAX_CONCURRENT_DOCKER_CREATE:-${STATIC_CAPACITY_LIMIT}}"
export SWE_POOL_ALLOCATE_MIN_INTERVAL_SEC="${SWE_POOL_ALLOCATE_MIN_INTERVAL_SEC:-0.05}"
export SWE_DOCKER_CREATE_MIN_INTERVAL_SEC="${SWE_DOCKER_CREATE_MIN_INTERVAL_SEC:-0.05}"
export SWE_POOL_HEALTH_CHECK_FAILURE_THRESHOLD="${SWE_POOL_HEALTH_CHECK_FAILURE_THRESHOLD:-3}"
export SWE_ROLLOUT_TIMEOUT="${SWE_ROLLOUT_TIMEOUT:-1800}"
export SWE_AGENT_RUNTIME_TIMEOUT="${SWE_AGENT_RUNTIME_TIMEOUT:-${SWE_ROLLOUT_TIMEOUT}}"
export SWE_EVAL_TIMEOUT="${SWE_EVAL_TIMEOUT:-${SWE_ROLLOUT_TIMEOUT}}"
export PYTHONUNBUFFERED="${PYTHONUNBUFFERED:-1}"
export PYTHONFAULTHANDLER="${PYTHONFAULTHANDLER:-1}"

{
    echo "TS=${TS}"
    echo "EXPORT_ROOT=${EXPORT_ROOT}"
    echo "LOG_DIR=${LOG_DIR}"
    echo "SWE_SAVE_TRAJ_DIR=${SWE_SAVE_TRAJ_DIR}"
    echo "DEBUG_MODE=${DEBUG_MODE}"
    echo "NUM_ROLLOUT=${NUM_ROLLOUT}"
    echo "ROLLOUT_BATCH_SIZE=${ROLLOUT_BATCH_SIZE}"
    echo "N_SAMPLES_PER_PROMPT=${N_SAMPLES_PER_PROMPT}"
    echo "OVER_SAMPLING_BATCH_SIZE=${OVER_SAMPLING_BATCH_SIZE}"
    echo "TARGET_TOTAL_SAMPLES=${TARGET_TOTAL_SAMPLES}"
    echo "SWE_CHECKPOINT_POLICY=${SWE_CHECKPOINT_POLICY}"
    echo "SWE_ADAPTIVE_TAIL_ROOT=${SWE_ADAPTIVE_TAIL_ROOT}"
    echo "SWE_ADAPTIVE_CHECKPOINT_BUDGET_SEC=${SWE_ADAPTIVE_CHECKPOINT_BUDGET_SEC}"
    echo "SWE_ADAPTIVE_DECISION_INTERVAL_SEC=${SWE_ADAPTIVE_DECISION_INTERVAL_SEC}"
    echo "SWE_ADAPTIVE_FAILURE_PROB=${SWE_ADAPTIVE_FAILURE_PROB}"
    echo "SWE_ADAPTIVE_MIN_DELTA_ENV_COST_SEC=${SWE_ADAPTIVE_MIN_DELTA_ENV_COST_SEC}"
    echo "SWE_ADAPTIVE_MIN_STEPS_BETWEEN_CHECKPOINTS=${SWE_ADAPTIVE_MIN_STEPS_BETWEEN_CHECKPOINTS}"
    echo "SWE_FAULT_INJECTION_ENABLE=${SWE_FAULT_INJECTION_ENABLE}"
    echo "SWE_FAULT_INJECTION_PROB=${SWE_FAULT_INJECTION_PROB}"
    echo "STATIC_MAX_CONCURRENCY=${STATIC_MAX_CONCURRENCY}"
    echo "SWE_STATIC_CAPACITY_HEADROOM=${SWE_STATIC_CAPACITY_HEADROOM}"
    echo "STATIC_CAPACITY_LIMIT=${STATIC_CAPACITY_LIMIT}"
    echo "SWE_MAX_CONCURRENT=${SWE_MAX_CONCURRENT}"
    echo "SWE_POOL_MAX_TOTAL_LEASES=${SWE_POOL_MAX_TOTAL_LEASES}"
    echo "SWE_MAX_CONTAINERS_PER_NODE=${SWE_MAX_CONTAINERS_PER_NODE}"
    echo "SWE_POOL_MAX_CONCURRENT_ALLOCATES=${SWE_POOL_MAX_CONCURRENT_ALLOCATES}"
    echo "SWE_MAX_CONCURRENT_DOCKER_CREATE=${SWE_MAX_CONCURRENT_DOCKER_CREATE}"
    echo "SWE_POOL_ALLOCATE_MIN_INTERVAL_SEC=${SWE_POOL_ALLOCATE_MIN_INTERVAL_SEC}"
    echo "SWE_DOCKER_CREATE_MIN_INTERVAL_SEC=${SWE_DOCKER_CREATE_MIN_INTERVAL_SEC}"
    echo "SWE_POOL_HEALTH_CHECK_FAILURE_THRESHOLD=${SWE_POOL_HEALTH_CHECK_FAILURE_THRESHOLD}"
    echo "SWE_ROLLOUT_TIMEOUT=${SWE_ROLLOUT_TIMEOUT}"
    echo "SWE_AGENT_RUNTIME_TIMEOUT=${SWE_AGENT_RUNTIME_TIMEOUT}"
    echo "SWE_EVAL_TIMEOUT=${SWE_EVAL_TIMEOUT}"
    echo "SWE_ENV_SERVER_URL=${SWE_ENV_SERVER_URL:-}"
    echo "SWE_EXEC_SERVER_URLS=${SWE_EXEC_SERVER_URLS:-}"
} | tee "${ENV_LOG}"

echo "[checkpoint-debug] command=bash ${SCRIPT_DIR}/run_swe_rl_static_rollout_only_baseline_128.sh $*"

exec bash "${SCRIPT_DIR}/run_swe_rl_static_rollout_only_baseline_128.sh" "$@"
