#!/bin/bash

# Rollout-only debug launcher for SWE online env docker scheduler.
# It reuses run_swe_rl.sh infra but switches entrypoint to rollout-only async loop.
#
# Usage:
#   bash swe-rl/scripts/run_swe_rl_online_scheduler_rollout_only_debug.sh

set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"
SWE_RL_DIR="$(cd -- "${SCRIPT_DIR}/.." &>/dev/null && pwd)"
SLIME_DIR="$(cd -- "${SWE_RL_DIR}/../slime" &>/dev/null && pwd)"
EXPORT_ROOT=${EXPORT_ROOT:-"${SWE_RL_DIR}/../export"}

# Rollout shape for this debug entrypoint.
# Keep the default profile fully synchronous unless the caller explicitly overrides it.
export DEBUG_MODE=${DEBUG_MODE:-1}
export NUM_ROLLOUT=${NUM_ROLLOUT:-1}
export ROLLOUT_BATCH_SIZE=${ROLLOUT_BATCH_SIZE:-64}
export N_SAMPLES_PER_PROMPT=${N_SAMPLES_PER_PROMPT:-8}
TARGET_TOTAL_SAMPLES=$((ROLLOUT_BATCH_SIZE * N_SAMPLES_PER_PROMPT))
export SWE_SGLANG_SERVER_CONCURRENCY=${SWE_SGLANG_SERVER_CONCURRENCY:-1048576}
export SWE_SCHED_INTERNAL_MAX_INFLIGHT=${SWE_SCHED_INTERNAL_MAX_INFLIGHT:-${SWE_SGLANG_SERVER_CONCURRENCY}}
TARGET_TOTAL_SAMPLES=${TARGET_TOTAL_SAMPLES:-$((ROLLOUT_BATCH_SIZE * N_SAMPLES_PER_PROMPT))}

# Turn on the online scheduler explicitly for this launcher.
export SWE_ENABLE_ONLINE_ENV_DOCKER_SCHEDULER=${SWE_ENABLE_ONLINE_ENV_DOCKER_SCHEDULER:-1}

# Scheduler budget aggressiveness.
# These knobs decide how optimistic admission can be relative to observed free
# memory / CPU / disk. Larger oversell means higher target concurrency.
export SWE_SCHED_SAMPLING_INTERVAL_SEC=${SWE_SCHED_SAMPLING_INTERVAL_SEC:-0.5}
export SWE_SCHED_SAFETY_MARGIN=${SWE_SCHED_SAFETY_MARGIN:-0.95}
export SWE_SCHED_MEMORY_OVERSELL_RATIO=${SWE_SCHED_MEMORY_OVERSELL_RATIO:-2.5}
export SWE_SCHED_MEMORY_PEAK_SCALE=${SWE_SCHED_MEMORY_PEAK_SCALE:-0.8}
export SWE_SCHED_CPU_OVERSELL_RATIO=${SWE_SCHED_CPU_OVERSELL_RATIO:-30} # 108 / num of GPU 
export SWE_SCHED_DISK_READ_OVERSELL_RATIO=${SWE_SCHED_DISK_READ_OVERSELL_RATIO:-1000.0}
export SWE_SCHED_DISK_WRITE_OVERSELL_RATIO=${SWE_SCHED_DISK_WRITE_OVERSELL_RATIO:-1000.0}
export SWE_SCHED_MAX_UNKNOWN_REPO_CONCURRENCY=${SWE_SCHED_MAX_UNKNOWN_REPO_CONCURRENCY:-128}


# Startup ramp control.
# `active_prompts` is counted per sample prompt, so the synchronous default cap is
# the rollout's total sample count.
export SWE_SCHED_STARTUP_MAX_ACTIVE_PROMPTS=${SWE_SCHED_STARTUP_MAX_ACTIVE_PROMPTS:-${TARGET_TOTAL_SAMPLES}}
export SWE_SCHED_STARTUP_CAP_DURATION_SEC=${SWE_SCHED_STARTUP_CAP_DURATION_SEC:-1}

# Resource signal source.
# This debug launcher defaults to pure online scheduling: no historical resource
# profiles are loaded, and admission is driven only by realtime server signals
# plus locally tracked active requests.
export SWE_SCHED_DISABLE_LIVE_STATS_POLLING=${SWE_SCHED_DISABLE_LIVE_STATS_POLLING:-0}
export SWE_SCHED_ENABLE_LIVE_PROFILE_UPDATES=${SWE_SCHED_ENABLE_LIVE_PROFILE_UPDATES:-0}
export SWE_SCHED_MAX_STATS_REQUESTS_PER_ROUND=${SWE_SCHED_MAX_STATS_REQUESTS_PER_ROUND:-16}
export SWE_SCHED_STATS_REQUEST_SPACING_SEC=${SWE_SCHED_STATS_REQUEST_SPACING_SEC:-0.03}
export SWE_SCHED_USE_RESOURCE_STATS_DIR=${SWE_SCHED_USE_RESOURCE_STATS_DIR:-0}
export SWE_SCHED_USE_REALTIME_SERVER_MEMORY=${SWE_SCHED_USE_REALTIME_SERVER_MEMORY:-1}
export SWE_SCHED_USE_REALTIME_SERVER_CPU=${SWE_SCHED_USE_REALTIME_SERVER_CPU:-1}
export SWE_SCHED_USE_REALTIME_SERVER_DISK=${SWE_SCHED_USE_REALTIME_SERVER_DISK:-1}
export SWE_SCHED_SERVER_MEMORY_REFRESH_SEC=${SWE_SCHED_SERVER_MEMORY_REFRESH_SEC:-10}

export SWE_MAX_CONCURRENT_EVAL=512
export SWE_MAX_CONCURRENT_DIFF=512

# Debug logging and head-of-line mitigation.
# When preserve-order mode is on, repeated budget hits can requeue the head prompt.
export SWE_SCHED_VERBOSE_LOGGING=${SWE_SCHED_VERBOSE_LOGGING:-1}
export SWE_SCHED_BLOCKED_LOG_INTERVAL_SEC=${SWE_SCHED_BLOCKED_LOG_INTERVAL_SEC:-5}
export SWE_SCHED_VERBOSE_LOG_INTERVAL_SEC=${SWE_SCHED_VERBOSE_LOG_INTERVAL_SEC:-10}
export SWE_SCHED_HEAD_BLOCK_REQUEUE_THRESHOLD=${SWE_SCHED_HEAD_BLOCK_REQUEUE_THRESHOLD:-100}
export SWE_SCHED_HEAD_BLOCK_REQUEUE_OFFSET=${SWE_SCHED_HEAD_BLOCK_REQUEUE_OFFSET:-1}

# Priority / backlog shaping.
# `REALTIME_LOCAL_ACTIVE_DISCOUNT` keeps a discounted shadow reservation for locally
# admitted prompts on top of realtime server stats.
# export SWE_SCHED_DURATION_PRIORITY_WEIGHT=${SWE_SCHED_DURATION_PRIORITY_WEIGHT:-0.4}
export SWE_SCHED_DURATION_PRIORITY_REF_SEC=${SWE_SCHED_DURATION_PRIORITY_REF_SEC:-300}
export SWE_SCHED_REALTIME_LOCAL_ACTIVE_DISCOUNT=${SWE_SCHED_REALTIME_LOCAL_ACTIVE_DISCOUNT:-1.0}
export SWE_SCHED_PENDING_GROUP_WINDOW_MULTIPLIER=${SWE_SCHED_PENDING_GROUP_WINDOW_MULTIPLIER:-1.0}
export SWE_SCHED_PENDING_GROUP_WINDOW_EXTRA=${SWE_SCHED_PENDING_GROUP_WINDOW_EXTRA:-0}
export SWE_SCHED_PENDING_GROUP_WINDOW_CAP=${SWE_SCHED_PENDING_GROUP_WINDOW_CAP:-${ROLLOUT_BATCH_SIZE}}
export SWE_RESOURCE_STATS_DIR=${SWE_RESOURCE_STATS_DIR:-""}
export SWE_REPO_RESOURCE_STATS_PATH=${SWE_REPO_RESOURCE_STATS_PATH:-""}
export SLIME_ENABLE_ROLLING_OVERSAMPLING_REFILL=${SLIME_ENABLE_ROLLING_OVERSAMPLING_REFILL:-0}

# Persisted repo resource profile path is intentionally disabled by default for
# this pure-online debug launcher. Set `SWE_REPO_RESOURCE_STATS_PATH` explicitly
# if you want to re-enable cached historical profiles.

# Infra-side throughput controls.
# These do not decide whether a prompt may be admitted; they decide how quickly an
# admitted prompt can actually allocate leases and create containers.
export SWE_POOL_MAX_TOTAL_LEASES=${SWE_POOL_MAX_TOTAL_LEASES:-1024}
export SWE_MAX_CONTAINERS_PER_NODE=${SWE_MAX_CONTAINERS_PER_NODE:-1024}
export SWE_POOL_MAX_CONCURRENT_ALLOCATES=${SWE_POOL_MAX_CONCURRENT_ALLOCATES:-64}
export SWE_POOL_ALLOCATE_MIN_INTERVAL_SEC=${SWE_POOL_ALLOCATE_MIN_INTERVAL_SEC:-0.05}
export SWE_SCHED_DOCKER_CREATE_MAX_CONCURRENT=${SWE_SCHED_DOCKER_CREATE_MAX_CONCURRENT:-64}
export SWE_SCHED_DOCKER_CREATE_MIN_INTERVAL_SEC=${SWE_SCHED_DOCKER_CREATE_MIN_INTERVAL_SEC:-0.05}
export SWE_MAX_CONCURRENT_DOCKER_CREATE=${SWE_MAX_CONCURRENT_DOCKER_CREATE:-${SWE_SCHED_DOCKER_CREATE_MAX_CONCURRENT}}
export SWE_DOCKER_CREATE_MIN_INTERVAL_SEC=${SWE_DOCKER_CREATE_MIN_INTERVAL_SEC:-${SWE_SCHED_DOCKER_CREATE_MIN_INTERVAL_SEC}}
export SWE_SCHED_PRESERVE_PROMPT_ORDER=${SWE_SCHED_PRESERVE_PROMPT_ORDER:-"False"}

# Use the rollout-only async entrypoint so scheduler behavior can be measured without
# the rest of the training loop.
export TRAIN_ASYNC_ENTRY="${SLIME_DIR}/train_async_rollout_only.py"
export SLIME_EXTRA_ARGS="${SLIME_EXTRA_ARGS:---debug-rollout-only} --sglang-server-concurrency ${SWE_SGLANG_SERVER_CONCURRENCY}"

echo "[rollout-only-debug] TRAIN_ASYNC_ENTRY=${TRAIN_ASYNC_ENTRY}"
echo "[rollout-only-debug] SLIME_EXTRA_ARGS=${SLIME_EXTRA_ARGS}"
echo "[rollout-only-debug] SWE_ENABLE_ONLINE_ENV_DOCKER_SCHEDULER=${SWE_ENABLE_ONLINE_ENV_DOCKER_SCHEDULER}"
echo "[rollout-only-debug] SWE_SGLANG_SERVER_CONCURRENCY=${SWE_SGLANG_SERVER_CONCURRENCY}"
echo "[rollout-only-debug] SWE_SCHED_INTERNAL_MAX_INFLIGHT=${SWE_SCHED_INTERNAL_MAX_INFLIGHT}"
echo "[rollout-only-debug] SWE_SCHED_MEMORY_OVERSELL_RATIO=${SWE_SCHED_MEMORY_OVERSELL_RATIO}"
echo "[rollout-only-debug] SWE_SCHED_MEMORY_PEAK_SCALE=${SWE_SCHED_MEMORY_PEAK_SCALE}"
echo "[rollout-only-debug] SWE_SCHED_CPU_OVERSELL_RATIO=${SWE_SCHED_CPU_OVERSELL_RATIO}"
echo "[rollout-only-debug] SWE_SCHED_DISK_READ_OVERSELL_RATIO=${SWE_SCHED_DISK_READ_OVERSELL_RATIO}"
echo "[rollout-only-debug] SWE_SCHED_DISK_WRITE_OVERSELL_RATIO=${SWE_SCHED_DISK_WRITE_OVERSELL_RATIO}"
echo "[rollout-only-debug] SWE_SCHED_USE_REALTIME_SERVER_MEMORY=${SWE_SCHED_USE_REALTIME_SERVER_MEMORY}"
echo "[rollout-only-debug] SWE_SCHED_USE_REALTIME_SERVER_CPU=${SWE_SCHED_USE_REALTIME_SERVER_CPU}"
echo "[rollout-only-debug] SWE_SCHED_USE_REALTIME_SERVER_DISK=${SWE_SCHED_USE_REALTIME_SERVER_DISK}"
echo "[rollout-only-debug] SWE_SCHED_DISABLE_LIVE_STATS_POLLING=${SWE_SCHED_DISABLE_LIVE_STATS_POLLING}"
echo "[rollout-only-debug] SWE_SCHED_ENABLE_LIVE_PROFILE_UPDATES=${SWE_SCHED_ENABLE_LIVE_PROFILE_UPDATES}"
echo "[rollout-only-debug] SWE_SCHED_MAX_STATS_REQUESTS_PER_ROUND=${SWE_SCHED_MAX_STATS_REQUESTS_PER_ROUND}"
echo "[rollout-only-debug] SWE_SCHED_STATS_REQUEST_SPACING_SEC=${SWE_SCHED_STATS_REQUEST_SPACING_SEC}"
echo "[rollout-only-debug] SWE_SCHED_USE_RESOURCE_STATS_DIR=${SWE_SCHED_USE_RESOURCE_STATS_DIR}"
echo "[rollout-only-debug] SWE_SCHED_REALTIME_LOCAL_ACTIVE_DISCOUNT=${SWE_SCHED_REALTIME_LOCAL_ACTIVE_DISCOUNT}"
echo "[rollout-only-debug] SWE_RESOURCE_STATS_DIR=${SWE_RESOURCE_STATS_DIR}"
echo "[rollout-only-debug] SWE_REPO_RESOURCE_STATS_PATH=${SWE_REPO_RESOURCE_STATS_PATH}"
echo "[rollout-only-debug] SWE_SCHED_PRESERVE_PROMPT_ORDER=${SWE_SCHED_PRESERVE_PROMPT_ORDER}"
echo "[rollout-only-debug] SWE_SCHED_SERVER_MEMORY_REFRESH_SEC=${SWE_SCHED_SERVER_MEMORY_REFRESH_SEC}"
echo "[rollout-only-debug] SWE_SCHED_VERBOSE_LOGGING=${SWE_SCHED_VERBOSE_LOGGING}"
echo "[rollout-only-debug] SWE_SCHED_BLOCKED_LOG_INTERVAL_SEC=${SWE_SCHED_BLOCKED_LOG_INTERVAL_SEC}"
echo "[rollout-only-debug] SWE_SCHED_VERBOSE_LOG_INTERVAL_SEC=${SWE_SCHED_VERBOSE_LOG_INTERVAL_SEC}"
echo "[rollout-only-debug] SWE_SCHED_HEAD_BLOCK_REQUEUE_THRESHOLD=${SWE_SCHED_HEAD_BLOCK_REQUEUE_THRESHOLD}"
echo "[rollout-only-debug] SWE_SCHED_HEAD_BLOCK_REQUEUE_OFFSET=${SWE_SCHED_HEAD_BLOCK_REQUEUE_OFFSET}"
echo "[rollout-only-debug] SWE_SCHED_DURATION_PRIORITY_REF_SEC=${SWE_SCHED_DURATION_PRIORITY_REF_SEC}"
echo "[rollout-only-debug] NUM_ROLLOUT=${NUM_ROLLOUT}"
echo "[rollout-only-debug] ROLLOUT_BATCH_SIZE=${ROLLOUT_BATCH_SIZE}"
echo "[rollout-only-debug] N_SAMPLES_PER_PROMPT=${N_SAMPLES_PER_PROMPT}"
echo "[rollout-only-debug] SWE_SCHED_PENDING_GROUP_WINDOW_MULTIPLIER=${SWE_SCHED_PENDING_GROUP_WINDOW_MULTIPLIER}"
echo "[rollout-only-debug] SWE_SCHED_PENDING_GROUP_WINDOW_EXTRA=${SWE_SCHED_PENDING_GROUP_WINDOW_EXTRA}"
echo "[rollout-only-debug] SWE_SCHED_PENDING_GROUP_WINDOW_CAP=${SWE_SCHED_PENDING_GROUP_WINDOW_CAP}"
echo "[rollout-only-debug] SWE_SCHED_STARTUP_MAX_ACTIVE_PROMPTS=${SWE_SCHED_STARTUP_MAX_ACTIVE_PROMPTS}"
echo "[rollout-only-debug] SWE_POOL_MAX_CONCURRENT_ALLOCATES=${SWE_POOL_MAX_CONCURRENT_ALLOCATES}"
echo "[rollout-only-debug] SWE_POOL_ALLOCATE_MIN_INTERVAL_SEC=${SWE_POOL_ALLOCATE_MIN_INTERVAL_SEC}"
echo "[rollout-only-debug] SWE_MAX_CONCURRENT_DOCKER_CREATE=${SWE_MAX_CONCURRENT_DOCKER_CREATE}"
echo "[rollout-only-debug] SWE_DOCKER_CREATE_MIN_INTERVAL_SEC=${SWE_DOCKER_CREATE_MIN_INTERVAL_SEC}"
echo "[rollout-only-debug] TARGET_TOTAL_SAMPLES_PER_ROLLOUT=${TARGET_TOTAL_SAMPLES}"

exec bash "${SCRIPT_DIR}/run_swe_rl.sh" "$@"
