#!/bin/bash

# Shared defaults for the SWE-RL online-scheduler + adaptive-risk checkpoint launchers.
#
# This file is meant to be sourced by concrete launch scripts. It does not submit
# jobs by itself; it only exports the feature flags and runtime knobs that need to
# stay aligned across single-node debug runs and multi-node training runs.

swe_rl_apply_online_scheduler_adaptive_checkpoint_defaults() {
    if [[ -z "${SWE_RL_DIR:-}" ]]; then
        echo "SWE_RL_DIR must be set before sourcing common launcher defaults." >&2
        return 1
    fi

    # Synchronous rollout defaults shared across all launchers.
    # Keep the effective target equal to the rollout batch:
    # - one sample per prompt
    # - no oversampling beyond rollout_batch_size
    # - no rolling refill
    export DEBUG_MODE="${DEBUG_MODE:-0}"
    export NUM_ROLLOUT="${NUM_ROLLOUT:-1}"
    export ROLLOUT_BATCH_SIZE="${ROLLOUT_BATCH_SIZE:-128}"
    export N_SAMPLES_PER_PROMPT="${N_SAMPLES_PER_PROMPT:-1}"
    export OVER_SAMPLING_BATCH_SIZE="${OVER_SAMPLING_BATCH_SIZE:-${ROLLOUT_BATCH_SIZE}}"
    export SLIME_ENABLE_ROLLING_OVERSAMPLING_REFILL="${SLIME_ENABLE_ROLLING_OVERSAMPLING_REFILL:-0}"
    export TARGET_TOTAL_SAMPLES="${TARGET_TOTAL_SAMPLES:-$((ROLLOUT_BATCH_SIZE * N_SAMPLES_PER_PROMPT))}"

    if [[ "${OVER_SAMPLING_BATCH_SIZE}" -ne "${ROLLOUT_BATCH_SIZE}" ]]; then
        echo "Synchronous rollout requires OVER_SAMPLING_BATCH_SIZE == ROLLOUT_BATCH_SIZE, got ${OVER_SAMPLING_BATCH_SIZE} vs ${ROLLOUT_BATCH_SIZE}" >&2
        return 1
    fi

    if [[ "${SLIME_ENABLE_ROLLING_OVERSAMPLING_REFILL}" != "0" ]]; then
        echo "Synchronous rollout requires SLIME_ENABLE_ROLLING_OVERSAMPLING_REFILL=0, got ${SLIME_ENABLE_ROLLING_OVERSAMPLING_REFILL}" >&2
        return 1
    fi

    # Adaptive-risk checkpoint policy.
    export SWE_CHECKPOINT_POLICY="${SWE_CHECKPOINT_POLICY:-adaptive-risk}"
    export SWE_ADAPTIVE_TAIL_ROOT="${SWE_ADAPTIVE_TAIL_ROOT:-${SWE_RL_DIR}/../export/swe_rollouts_profile_20260325_083236}"
    export SWE_ADAPTIVE_CHECKPOINT_BUDGET_SEC="${SWE_ADAPTIVE_CHECKPOINT_BUDGET_SEC:-7.0}"
    export SWE_ADAPTIVE_DECISION_INTERVAL_SEC="${SWE_ADAPTIVE_DECISION_INTERVAL_SEC:-2.0}"
    export SWE_ADAPTIVE_FAILURE_PROB="${SWE_ADAPTIVE_FAILURE_PROB:-0.01}"
    export SWE_ADAPTIVE_MIN_DELTA_ENV_COST_SEC="${SWE_ADAPTIVE_MIN_DELTA_ENV_COST_SEC:-30}"
    export SWE_ADAPTIVE_MIN_STEPS_BETWEEN_CHECKPOINTS="${SWE_ADAPTIVE_MIN_STEPS_BETWEEN_CHECKPOINTS:-4}"

    # Optional server-side fault injection.
    export SWE_FAULT_INJECTION_ENABLE="${SWE_FAULT_INJECTION_ENABLE:-0}"
    export SWE_FAULT_INJECTION_PROB="${SWE_FAULT_INJECTION_PROB:-0.003}"

    # Online scheduler master switch.
    export SWE_ENABLE_ONLINE_ENV_DOCKER_SCHEDULER="${SWE_ENABLE_ONLINE_ENV_DOCKER_SCHEDULER:-1}"

    # Scheduler admission and budget knobs.
    export SWE_SCHED_SAMPLING_INTERVAL_SEC="${SWE_SCHED_SAMPLING_INTERVAL_SEC:-15}"
    export SWE_SCHED_SAFETY_MARGIN="${SWE_SCHED_SAFETY_MARGIN:-0.95}"
    export SWE_SCHED_MEMORY_OVERSELL_RATIO="${SWE_SCHED_MEMORY_OVERSELL_RATIO:-1.0}"
    export SWE_SCHED_MEMORY_PEAK_SCALE="${SWE_SCHED_MEMORY_PEAK_SCALE:-0.95}"
    export SWE_SCHED_CPU_OVERSELL_RATIO="${SWE_SCHED_CPU_OVERSELL_RATIO:-32}"
    export SWE_SCHED_MAX_UNKNOWN_REPO_CONCURRENCY="${SWE_SCHED_MAX_UNKNOWN_REPO_CONCURRENCY:-32}"

    # Startup ramp and realtime resource signal selection.
    export SWE_SCHED_STARTUP_MAX_ACTIVE_PROMPTS="${SWE_SCHED_STARTUP_MAX_ACTIVE_PROMPTS:-${TARGET_TOTAL_SAMPLES}}"
    export SWE_SCHED_STARTUP_CAP_DURATION_SEC="${SWE_SCHED_STARTUP_CAP_DURATION_SEC:-30}"
    export SWE_SCHED_DISABLE_LIVE_STATS_POLLING="${SWE_SCHED_DISABLE_LIVE_STATS_POLLING:-1}"
    export SWE_SCHED_USE_RESOURCE_STATS_DIR="${SWE_SCHED_USE_RESOURCE_STATS_DIR:-1}"
    export SWE_SCHED_USE_REALTIME_SERVER_MEMORY="${SWE_SCHED_USE_REALTIME_SERVER_MEMORY:-1}"
    export SWE_SCHED_USE_REALTIME_SERVER_CPU="${SWE_SCHED_USE_REALTIME_SERVER_CPU:-1}"
    export SWE_SCHED_USE_REALTIME_SERVER_DISK="${SWE_SCHED_USE_REALTIME_SERVER_DISK:-1}"
    export SWE_SCHED_SERVER_MEMORY_REFRESH_SEC="${SWE_SCHED_SERVER_MEMORY_REFRESH_SEC:-5}"

    # Logging and preserve-order behavior.
    export SWE_SCHED_VERBOSE_LOGGING="${SWE_SCHED_VERBOSE_LOGGING:-1}"
    export SWE_SCHED_BLOCKED_LOG_INTERVAL_SEC="${SWE_SCHED_BLOCKED_LOG_INTERVAL_SEC:-5}"
    export SWE_SCHED_VERBOSE_LOG_INTERVAL_SEC="${SWE_SCHED_VERBOSE_LOG_INTERVAL_SEC:-10}"
    export SWE_SCHED_HEAD_BLOCK_REQUEUE_THRESHOLD="${SWE_SCHED_HEAD_BLOCK_REQUEUE_THRESHOLD:-3}"
    export SWE_SCHED_HEAD_BLOCK_REQUEUE_OFFSET="${SWE_SCHED_HEAD_BLOCK_REQUEUE_OFFSET:-5}"
    export SWE_SCHED_PRESERVE_PROMPT_ORDER="${SWE_SCHED_PRESERVE_PROMPT_ORDER:-True}"

    # Priority shaping and shadow reservation tuning.
    export SWE_SCHED_DURATION_PRIORITY_WEIGHT="${SWE_SCHED_DURATION_PRIORITY_WEIGHT:-0.4}"
    export SWE_SCHED_DURATION_PRIORITY_REF_SEC="${SWE_SCHED_DURATION_PRIORITY_REF_SEC:-300}"
    export SWE_SCHED_REALTIME_LOCAL_ACTIVE_DISCOUNT="${SWE_SCHED_REALTIME_LOCAL_ACTIVE_DISCOUNT:-1.0}"
    export SWE_SCHED_INTERNAL_MAX_INFLIGHT="${SWE_SCHED_INTERNAL_MAX_INFLIGHT:-512}"
    export SWE_SCHED_PENDING_GROUP_WINDOW_MULTIPLIER="${SWE_SCHED_PENDING_GROUP_WINDOW_MULTIPLIER:-1.0}"
    export SWE_SCHED_PENDING_GROUP_WINDOW_EXTRA="${SWE_SCHED_PENDING_GROUP_WINDOW_EXTRA:-0}"
    export SWE_SCHED_PENDING_GROUP_WINDOW_CAP="${SWE_SCHED_PENDING_GROUP_WINDOW_CAP:-${ROLLOUT_BATCH_SIZE}}"

    # Persisted resource profiles reused across runs.
    export SWE_RESOURCE_STATS_DIR="${SWE_RESOURCE_STATS_DIR:-${SWE_RL_DIR}/resource_stats}"
    export SWE_REPO_RESOURCE_STATS_PATH="${SWE_REPO_RESOURCE_STATS_PATH:-${SWE_RL_DIR}/output/swe_rollouts/repo_resource_stats.json}"
    mkdir -p "$(dirname "${SWE_REPO_RESOURCE_STATS_PATH}")"

    # Control-plane throughput knobs.
    export SWE_POOL_MAX_CONCURRENT_ALLOCATES="${SWE_POOL_MAX_CONCURRENT_ALLOCATES:-8}"
    export SWE_POOL_ALLOCATE_MIN_INTERVAL_SEC="${SWE_POOL_ALLOCATE_MIN_INTERVAL_SEC:-0.05}"
    export SWE_SCHED_DOCKER_CREATE_MAX_CONCURRENT="${SWE_SCHED_DOCKER_CREATE_MAX_CONCURRENT:-8}"
    export SWE_SCHED_DOCKER_CREATE_MIN_INTERVAL_SEC="${SWE_SCHED_DOCKER_CREATE_MIN_INTERVAL_SEC:-0.05}"

    # Timeout / retry guardrails.
    export SWE_POOL_CREATE_TIMEOUT_SEC="${SWE_POOL_CREATE_TIMEOUT_SEC:-1800}"
    export SWE_POOL_HEALTH_CHECK_FAILURE_THRESHOLD="${SWE_POOL_HEALTH_CHECK_FAILURE_THRESHOLD:-3}"
    export SWE_ROLLOUT_TIMEOUT="${SWE_ROLLOUT_TIMEOUT:-2400}"
    export SWE_AGENT_RUNTIME_TIMEOUT="${SWE_AGENT_RUNTIME_TIMEOUT:-${SWE_ROLLOUT_TIMEOUT}}"
    export SWE_EVAL_TIMEOUT="${SWE_EVAL_TIMEOUT:-${SWE_ROLLOUT_TIMEOUT}}"
    export SWE_ENV_HTTP_MAX_RETRIES="${SWE_ENV_HTTP_MAX_RETRIES:-10}"
    export SWE_ALLOCATE_HTTP_MAX_RETRIES="${SWE_ALLOCATE_HTTP_MAX_RETRIES:-1}"
    export SWE_ENV_APP_MAX_RETRIES="${SWE_ENV_APP_MAX_RETRIES:-3}"
    export SWE_ALLOCATE_APP_MAX_RETRIES="${SWE_ALLOCATE_APP_MAX_RETRIES:-360}"
    export SWE_ENV_APP_RETRY_DELAY_SEC="${SWE_ENV_APP_RETRY_DELAY_SEC:-1.0}"
    export SWE_ENV_APP_RETRY_JITTER_SEC="${SWE_ENV_APP_RETRY_JITTER_SEC:-0.2}"
    export SWE_ENV_APP_RETRY_MAX_DELAY_SEC="${SWE_ENV_APP_RETRY_MAX_DELAY_SEC:-5.0}"

    # Runtime defaults shared by both launchers.
    export SGLANG_SERVER_CONCURRENCY="${SGLANG_SERVER_CONCURRENCY:-1024}"
    export PYTHONUNBUFFERED="${PYTHONUNBUFFERED:-1}"
    export PYTHONFAULTHANDLER="${PYTHONFAULTHANDLER:-1}"
    export LITELLM_MODEL_REGISTRY_PATH="${LITELLM_MODEL_REGISTRY_PATH:-${SWE_RL_DIR}/litellm.json}"
    export MSWEA_DOCKER_EXEC_MODE="${MSWEA_DOCKER_EXEC_MODE:-api}"
    export RAY_health_check_failure_threshold="${RAY_health_check_failure_threshold:-20}"
    export RAY_health_check_period_ms="${RAY_health_check_period_ms:-5000}"
    export RAY_health_check_timeout_ms="${RAY_health_check_timeout_ms:-30000}"
    export RAY_num_heartbeats_timeout="${RAY_num_heartbeats_timeout:-60}"
    export RAY_EXPERIMENTAL_NOSET_CUDA_VISIBLE_DEVICES="${RAY_EXPERIMENTAL_NOSET_CUDA_VISIBLE_DEVICES:-1}"
    export PYTORCH_CUDA_ALLOC_CONF="${PYTORCH_CUDA_ALLOC_CONF:-max_split_size_mb:2048,expandable_segments:True}"
}

swe_rl_print_online_scheduler_adaptive_checkpoint_summary() {
    local prefix="${1:-[swe-launch]}"
    echo "${prefix} DEBUG_MODE=${DEBUG_MODE}"
    echo "${prefix} NUM_ROLLOUT=${NUM_ROLLOUT}"
    echo "${prefix} ROLLOUT_BATCH_SIZE=${ROLLOUT_BATCH_SIZE}"
    echo "${prefix} N_SAMPLES_PER_PROMPT=${N_SAMPLES_PER_PROMPT}"
    echo "${prefix} OVER_SAMPLING_BATCH_SIZE=${OVER_SAMPLING_BATCH_SIZE}"
    echo "${prefix} TARGET_TOTAL_SAMPLES=${TARGET_TOTAL_SAMPLES}"
    echo "${prefix} SLIME_ENABLE_ROLLING_OVERSAMPLING_REFILL=${SLIME_ENABLE_ROLLING_OVERSAMPLING_REFILL}"
    echo "${prefix} SWE_ENABLE_ONLINE_ENV_DOCKER_SCHEDULER=${SWE_ENABLE_ONLINE_ENV_DOCKER_SCHEDULER}"
    echo "${prefix} SWE_CHECKPOINT_POLICY=${SWE_CHECKPOINT_POLICY}"
    echo "${prefix} SWE_ADAPTIVE_TAIL_ROOT=${SWE_ADAPTIVE_TAIL_ROOT}"
    echo "${prefix} SWE_ADAPTIVE_CHECKPOINT_BUDGET_SEC=${SWE_ADAPTIVE_CHECKPOINT_BUDGET_SEC}"
    echo "${prefix} SWE_ADAPTIVE_DECISION_INTERVAL_SEC=${SWE_ADAPTIVE_DECISION_INTERVAL_SEC}"
    echo "${prefix} SWE_ADAPTIVE_FAILURE_PROB=${SWE_ADAPTIVE_FAILURE_PROB}"
    echo "${prefix} SWE_SCHED_MEMORY_OVERSELL_RATIO=${SWE_SCHED_MEMORY_OVERSELL_RATIO}"
    echo "${prefix} SWE_SCHED_MEMORY_PEAK_SCALE=${SWE_SCHED_MEMORY_PEAK_SCALE}"
    echo "${prefix} SWE_SCHED_CPU_OVERSELL_RATIO=${SWE_SCHED_CPU_OVERSELL_RATIO}"
    echo "${prefix} SWE_SCHED_USE_REALTIME_SERVER_MEMORY=${SWE_SCHED_USE_REALTIME_SERVER_MEMORY}"
    echo "${prefix} SWE_SCHED_USE_REALTIME_SERVER_CPU=${SWE_SCHED_USE_REALTIME_SERVER_CPU}"
    echo "${prefix} SWE_SCHED_USE_REALTIME_SERVER_DISK=${SWE_SCHED_USE_REALTIME_SERVER_DISK}"
    echo "${prefix} SWE_SCHED_STARTUP_MAX_ACTIVE_PROMPTS=${SWE_SCHED_STARTUP_MAX_ACTIVE_PROMPTS}"
    echo "${prefix} SWE_SCHED_REALTIME_LOCAL_ACTIVE_DISCOUNT=${SWE_SCHED_REALTIME_LOCAL_ACTIVE_DISCOUNT}"
    echo "${prefix} SWE_SCHED_INTERNAL_MAX_INFLIGHT=${SWE_SCHED_INTERNAL_MAX_INFLIGHT}"
    echo "${prefix} SWE_SCHED_PRESERVE_PROMPT_ORDER=${SWE_SCHED_PRESERVE_PROMPT_ORDER}"
    echo "${prefix} LITELLM_MODEL_REGISTRY_PATH=${LITELLM_MODEL_REGISTRY_PATH}"
    echo "${prefix} SWE_REPO_RESOURCE_STATS_PATH=${SWE_REPO_RESOURCE_STATS_PATH}"
    echo "${prefix} SWE_POOL_MAX_TOTAL_LEASES=${SWE_POOL_MAX_TOTAL_LEASES}"
    echo "${prefix} SWE_POOL_MAX_CONCURRENT_ALLOCATES=${SWE_POOL_MAX_CONCURRENT_ALLOCATES}"
    echo "${prefix} SWE_MAX_CONCURRENT_DOCKER_CREATE=${SWE_MAX_CONCURRENT_DOCKER_CREATE}"
    echo "${prefix} SWE_MAX_CONCURRENT_EVAL=${SWE_MAX_CONCURRENT_EVAL}"
    echo "${prefix} SWE_MAX_CONCURRENT_DIFF=${SWE_MAX_CONCURRENT_DIFF}"
    echo "${prefix} SWE_POOL_CREATE_TIMEOUT_SEC=${SWE_POOL_CREATE_TIMEOUT_SEC}"
    echo "${prefix} SWE_ROLLOUT_TIMEOUT=${SWE_ROLLOUT_TIMEOUT}"
}
